name: kanachat
description: "An Open Source ChatBot Application using Google Vertex AI build with Flutter."
publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  cupertino_icons: ^1.0.8
  firebase_core: ^3.13.0
  firebase_vertexai: ^1.6.0
  flutter:
    sdk: flutter
  flutter_animate: ^4.5.2
  flutter_bloc: ^9.1.1
  flutter_dotenv: ^5.2.1
  flutter_slidable: ^4.0.0
  fpdart: ^1.1.1
  get_it: ^8.0.3
  go_router: ^15.1.2
  google_fonts: ^6.2.1
  gpt_markdown: ^1.0.18
  hydrated_bloc: ^10.0.0
  internet_connection_checker_plus: ^2.7.2
  intl: ^0.20.2
  path: ^1.9.1
  path_provider: ^2.1.5
  solar_icons: ^0.0.5
  sqflite: ^2.4.2
  uuid: ^4.5.1

dev_dependencies:
  change_app_package_name: ^1.5.0
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
