// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB1qPPv_PAT8xE4jX2hqdRO3NF1Csozu8g',
    appId: '1:379941987155:android:93c2082075e246f24db7a6',
    messagingSenderId: '379941987155',
    projectId: 'kanachat-1b4f7',
    storageBucket: 'kanachat-1b4f7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDAntB_il4OqlOR3pMLooatfssbrFOeqtc',
    appId: '1:379941987155:ios:5c746391add9a4634db7a6',
    messagingSenderId: '379941987155',
    projectId: 'kanachat-1b4f7',
    storageBucket: 'kanachat-1b4f7.firebasestorage.app',
    iosBundleId: 'id.sofyan.kanachat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDAntB_il4OqlOR3pMLooatfssbrFOeqtc',
    appId: '1:379941987155:ios:93f5a1802f8c24114db7a6',
    messagingSenderId: '379941987155',
    projectId: 'kanachat-1b4f7',
    storageBucket: 'kanachat-1b4f7.firebasestorage.app',
    iosBundleId: 'com.example.kanachat',
  );

}